message( STATUS "Install prefix:    ${CMAKE_INSTALL_PREFIX}")
message( STATUS "------------------------------------------------------------------" )
message( STATUS "CMake Generator:   ${CMAKE_GENERATOR}" )
message( STATUS "CMAKE_BUILD_TYPE:  ${CMAKE_BUILD_TYPE}" )
message( STATUS "Compiler info: ${CMAKE_C_COMPILER_ID} (${CMAKE_C_COMPILER}) ; version: ${CMAKE_C_COMPILER_VERSION}")
message( STATUS "CMAKE_C_STANDARD:${CMAKE_C_STANDARD}" )
message( STATUS " --- Compiler flags --- ")
message( STATUS "General:           ${CMAKE_C_FLAGS}" )
message( STATUS "Extra:             ${EXTRA_COMPILE_FLAGS}" )
message( STATUS "Debug:             ${CMAKE_C_FLAGS_DEBUG}" )
message( STATUS "Release:           ${CMAKE_C_FLAGS_RELEASE}" )
message( STATUS "RelWithDebInfo:    ${CMAKE_C_FLAGS_RELWITHDEBINFO}" )
message( STATUS "MinSizeRel:        ${CMAKE_C_FLAGS_MINSIZEREL}" )
message( STATUS " --- Linker flags --- ")
message( STATUS "General:           ${CMAKE_EXE_LINKER_FLAGS}" )
message( STATUS "Debug:             ${CMAKE_EXE_LINKER_FLAGS_DEBUG}" )
message( STATUS "Release:           ${CMAKE_EXE_LINKER_FLAGS_RELEASE}" )
message( STATUS "RelWithDebInfo:    ${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO}" )
message( STATUS "MinSizeRel:        ${CMAKE_EXE_LINKER_FLAGS_MINSIZEREL}" )
message( STATUS "" )
message( STATUS "Compiler Options")
message( STATUS "" )
message( STATUS "------------------------------------------------------------------" )
